server:
  port: 9000

# 추가 설정 - R2DBC에서 Database로 나가는 쿼리를 보고 싶으면 아래처럼 로깅레벨을 설정해야 함
logging:
  level:
    org.springframework.r2dbc.core: info
    root: debug
# ffmpeg 커널 패스
path:
  ffmpeg: "ffmpeg"
  ffprobe: "ffprobe"


volume:
  # root dir 부터 시작 ex) app/media
  media: "app/media"
