server:
  port: 8080

# 추가 설정 - R2DBC에서 Database로 나가는 쿼리를 보고 싶으면 아래처럼 로깅레벨을 설정해야 함
logging:
  level:
    org.springframework.r2dbc.core: debug
# ffmpeg 커널 패스
path:
  ffmpeg: "/opt/homebrew/bin/ffmpeg"
  ffprobe: "/opt/homebrew/bin/ffprobe"

volume:
  # 시크릿 파일 패스 file: classpath:
  secret: "classpath:secret-dev.yml"
  media: "app/media"
